default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: edify_development
  username: <%= Rails.application.secrets.db_username %>
  password: <%= Rails.application.secrets.db_password %>
  host: localhost

test:
  <<: *default
  database: edify_test
  username: postgres
  host: localhost
  username: <%= Rails.application.secrets.db_username %>
  password: <%= Rails.application.secrets.db_password %>

production:
  <<: *default
  database: edify_production
  username: <%= Rails.application.secrets.db_username %>
  password: <%= Rails.application.secrets.db_password %>
