default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: edify_development
  username: landrywj
  host: localhost
  
test:
  <<: *default
  database: edify_test
  username: landrywj
  host: localhost

production:
  <<: *default
  database: edify_production
  username: Rails.application.secrets.db_username
  password: Rails.application.secrets.db_password
